ruby-grape/grape-swagger-entity

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb

`grape-entity` raises an error if `values:` key is passed outside of the `documentation` hash:
```ruby
expose :thing2,  values: [1, 2, 3], documentation: { type: Integer }
```
However, `grape-swagger-entity` has business logic requiring the `values:` key to be passed like the above example.
This PR changes the business logic to expect the `values:` key inside the `documentation:` hash as such:
```ruby
expose :thing2, documentation: { type: Integer, values: [1, 2, 3] }
```

Generate enum property if values key is passed in documentation

---

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb
spec/grape-swagger/entity/parser_spec.rb
spec/spec_helper.rb
spec/support/shared_contexts/this_api.rb

In some cases, we want to document entities or response definitions separate from an endpoint. This allows us to generate documentation while passing an endpoint as nil.

Allow parsing Entity with no endpoint

---

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb

It crashes on `master` because it can't find original exposure

Fix a case when nested attribute has an alias

---

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb

There is another bug: `required: true` is not supported for nested attributes. I added test case but have no idea how to fix it. 
It seems there is a flaw in design: there is part in `grape-swagger` that wraps entity and adds `required` key along with `properties`. But if an attribute is nested, then `grape-swagger-entity` wraps it with the same structure as `grape-swagger`, but without required. 
Both gems does the same job, and it feels wrong

Attempt to fix required properties for nested attributes

---

.rubocop.yml
CHANGELOG.md
grape-swagger-entity.gemspec
lib/grape-swagger/entity/attribute_parser.rb
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb
spec/spec_helper.rb

I recently tried to use the `read_only` fields feature, only to find it didn't work. As far as I can tell, this is the format as per the Swagger spec. Please see my comment in the original PR at https://github.com/ruby-grape/grape-swagger-entity/pull/26.

Fix issue with read_only fields

---

.rubocop.yml
lib/grape-swagger/entity/attribute_parser.rb
lib/grape-swagger/entity/parser.rb

Fixes Rubocop violations:
```
Running RuboCop...
.rubocop.yml: Style/FileName has the wrong namespace - should be Naming
.rubocop.yml: Style/IndentHash has the wrong namespace - should be Layout
Inspecting 15 files
...........CC..
Offenses:
lib/grape-swagger/entity/parser.rb:48:11: C: Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
next unless documentation
^^^^^^^^^^^^^^^^^^^^^^^^^
lib/grape-swagger/entity/parser.rb:94:9: C: Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
return hash if required.empty?
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/grape-swagger/entity/attribute_parser.rb:44:9: C: Layout/EmptyLineAfterGuardClause: Add empty line after guard clause.
return false if value.nil?
^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

Fix Rubocop violations

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

Adds support for `minItems`, `maxItems` and `uniqueItems` for `Arrays` (`is_array: true`) as described in the [`Schema Object` of the OpenAPI 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object).
The [`grape-entity` documentation](https://github.com/ruby-grape/grape-entity/tree/v0.7.1#documentation) mentions that the `documentation` bubbles up but this is not the case for the above attributes.

Add support for minItems, maxItems and uniqueItems

---

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entity/parser_spec.rb
spec/support/shared_contexts/this_api.rb

Currently there's no way of avoding the exposure of an entity attribute.
Sometimes there are internal and conditional attributes that are not
important to be known in the documentation to whoever is consuming that
entity.
In this case, we are simply checking if there's a `hidden` attribute in
the `documentation` options and we skip it when parsing the entity
attributes.
Signed-off-by: Vítor Avelino <vavelino@suse.com>

Added support for hidden option for documentation

---

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb

Models 
```ruby
class Picture < ApplicationRecord
 belongs_to :imageable, polymorphic: true
end
class Employee < ApplicationRecord
  has_many :pictures, as: :imageable
end
class Product < ApplicationRecord
  has_many :pictures, as: :imageable
end
```
Entity
```ruby
class Entities::Employee <Grape::Entity
end
class Entities::Product <Grape::Entity
end
class Picture < Grape::Entity
expose :imageable, as: employee, if: lambda { |ins, _| ins.kind_of?(Employee) }, using: Entities::Employee
expose :imageable, as: product, if: lambda { |ins, _| ins.kind_of?(Product) }, using: Entities::Product
end
```
Current parser implements don't cares about same name `expose`.
I add new inner class `Alias` and create instance to use key of `memo` hash if `:as` option enabled.
When parse grape entity params, …

Fix to avoid conflict with Polymorphic model

---

.rubocop.yml
Gemfile

Fixes build by updating and locking `rubocop` gem to version `~> 0.68.1`.
Version `0.68.1` is the last version that supports Ruby `2.2`, since [version `0.69.0` dropped](https://github.com/rubocop-hq/rubocop/blob/v0.69.0/CHANGELOG.md#changes) Ruby `2.2` support in https://github.com/rubocop-hq/rubocop/issues/6945.
Additionally `Layout/IndentHash` has been [renamed to `IndentFirstHashElement` in `0.68.0`](https://github.com/rubocop-hq/rubocop/blob/v0.68.0/CHANGELOG.md#changes).
We should probably consider dropping support for Ruby `2.2`, in a separate MR, since it has [reached EOL](https://www.ruby-lang.org/en/news/2018/06/20/support-of-ruby-2-2-has-ended/) since March 2018.

Update rubocop gem to version ~> 0.68.1

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

Adds support for `minLength`, `maxLength` for `Strings` (`type: String`) as described in the [`Schema Object` of the OpenAPI 2.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object).
This is very similar to #37.

Add support for minLength and maxLength

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

Fix for issue https://github.com/ruby-grape/grape-swagger-entity/issues/45

fixed issue where a boolean example value of false would not display in swagger file

---

.github/workflows/test.yml
CHANGELOG.md
Gemfile
grape-swagger-entity.gemspec

* Update grape entity dep
* Min supported Ruby is 3.0 since that's what grape-swagger specifies.
* Add Ruby 3.3 to build matrix

Various build updates

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

Right now the `example` documentation key is ignored. The first commit on its own fixes this, but then I opted to refactor `AttributeParser#call` to make it harder to miss adding support for a documentation key for a `using` exposure.

Properly render `example` for array exposure done using another entity

---

.rubocop_todo.yml
CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

This adds [support for generating the `minimum` and `maximum` swagger keywords](https://swagger.io/docs/specification/data-models/data-types/#range). 
There are two ways to produce these keywords:
```
documentation: {
minimum: 0,
maximum: 100,
}
```
```
documentation: {
values: 0..100,
}
```

Add support for minimum and maximum

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

This bug was introduced in
https://github.com/ruby-grape/grape-swagger-entity/pull/68
I've added a regression spec and a fix for this, along with a tiny bit of cleanup because there seem to have been some confusion in the naming of variables.

Fix enum values of array attributes

---

CHANGELOG.md
lib/grape-swagger/entity/parser.rb
spec/grape-swagger/entities/response_model_spec.rb

Hello,
This PR want to fix a limitation of this gem with nested expose on child entities.
I noticed that when an entity inherits from another, nested exposures are not merged (as opposed to Grape Entity) in the definition object. For instance this won't work:
```ruby
class Nested < Grape::Entity
expose :nested, documentation: { type: Hash, desc: 'Nested entity' } do
expose :some1, documentation: { type: 'String', desc: 'Nested some 1' }
expose :some2, documentation: { type: 'String', desc: 'Nested some 2' }
end
end
class NestedChild < Nested
expose :nested, documentation: { type: Hash, desc: 'Nested entity' } do
expose :some3, documentation: { type: 'String', desc: 'Nested some 3' }
end
end
```
Would produce this definition:
```json
{
"definitions": {
"Nested": {
"type": "object", …
```

Ensure inherited nested exposures are merged

---

.github/workflows/test.yml
.rubocop_todo.yml
CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entities/response_model_spec.rb
spec/grape-swagger/entity/attribute_parser_spec.rb
spec/support/shared_contexts/custom_type_parser.rb

Improves the handling of unconventional entity class names and enhances support for diverse types in Swagger documentation generation.
- Fixed `ambiguous_model_type?` to correctly identify entities with non-standard class names.
- Introduced `primitive_type?` for clearer handling of primitives and additional non-class types (string, array).
- Enabled support for custom type parsers to handle registered types for parsing.

Fix handling of entity with class names without "Entity" or "Entities"

---

.github/workflows/test.yml
CHANGELOG.md
Gemfile

This PR makes it easier for us to test the gem with different versions of grape and Ruby. By expanding our test matrix and updating the Gemfile, we can check that our changes work with a wider range of grape versions. This helps catch any issues early and ensures our gem stays compatible with future updates.

Update CI matrix and Gemfile for multi-version grape testing

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entities/response_model_spec.rb
spec/support/shared_contexts/this_api.rb

This PR fixes an issue where specifying a class like `Time` for the `type` option in `expose` documentation resulted in an error instead of generating the correct Swagger/OpenAPI specification.
This functionality was working correctly in v0.5.5 but regressed after PR #75, leading to the following error:
```
GrapeSwagger::Errors::UnregisteredParser:
No parser registered for Time.
```
The `primitive_type?` method now uses `GrapeSwagger::DocMethods::DataType.call` to resolve the type name before checking if it's a primitive type.
This ensures that types like `Time` are correctly identified as strings with the `date-time` format, restoring the previous behavior.
@numbata Could you please take a look at this PR when you have a chance?

Fix Correctly handle class types like Time in documentation

---

CHANGELOG.md
lib/grape-swagger/entity/attribute_parser.rb
spec/grape-swagger/entity/attribute_parser_spec.rb

This pull request addresses an issue in the `GrapeSwagger::Entity::AttributeParser` where the `Grape::API::Boolean` and other type was not being recognized as a primitive type during Swagger schema generation.
These changes ensure that primitive types are correctly represented in the generated Swagger documentation.

Fix: Recognize Grape::API::Boolean as a primitive type
